# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(514, 600)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 0, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 0);")
        self.label.setObjectName("label")
        self.Name = QtWidgets.QLabel(self.centralwidget)
        self.Name.setGeometry(QtCore.QRect(160, 80, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        self.Name.setFont(font)
        self.Name.setStyleSheet("color: rgb(255, 255, 0);")
        self.Name.setObjectName("Name")
        self.Username = QtWidgets.QLabel(self.centralwidget)
        self.Username.setGeometry(QtCore.QRect(160, 160, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        self.Username.setFont(font)
        self.Username.setStyleSheet("color: rgb(255, 255, 0);")
        self.Username.setObjectName("Username")
        self.Password = QtWidgets.QLabel(self.centralwidget)
        self.Password.setGeometry(QtCore.QRect(160, 240, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        self.Password.setFont(font)
        self.Password.setStyleSheet("color: rgb(255, 255, 0);")
        self.Password.setObjectName("Password")
        self.ConPassword = QtWidgets.QLabel(self.centralwidget)
        self.ConPassword.setGeometry(QtCore.QRect(160, 320, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        self.ConPassword.setFont(font)
        self.ConPassword.setStyleSheet("color: rgb(255, 255, 0);")
        self.ConPassword.setObjectName("ConPassword")
        self.TxtName = QtWidgets.QLineEdit(self.centralwidget)
        self.TxtName.setGeometry(QtCore.QRect(160, 120, 191, 21))
        self.TxtName.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.TxtName.setObjectName("TxtName")
        self.TxtUsername = QtWidgets.QLineEdit(self.centralwidget)
        self.TxtUsername.setGeometry(QtCore.QRect(160, 200, 191, 21))
        self.TxtUsername.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.TxtUsername.setObjectName("TxtUsername")
        self.TxtPasword = QtWidgets.QLineEdit(self.centralwidget)
        self.TxtPasword.setGeometry(QtCore.QRect(160, 280, 191, 21))
        self.TxtPasword.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.TxtPasword.setObjectName("TxtPasword")
        self.TxtConPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.TxtConPassword.setGeometry(QtCore.QRect(160, 360, 191, 21))
        self.TxtConPassword.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.TxtConPassword.setObjectName("TxtConPassword")
        self.BtnLogin = QtWidgets.QPushButton(self.centralwidget)
        self.BtnLogin.setGeometry(QtCore.QRect(320, 450, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        self.BtnLogin.setFont(font)
        self.BtnLogin.setStyleSheet("color: rgb(255, 255, 0);")
        self.BtnLogin.setObjectName("BtnLogin")
        self.BtnRegister = QtWidgets.QPushButton(self.centralwidget)
        self.BtnRegister.setGeometry(QtCore.QRect(80, 450, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        self.BtnRegister.setFont(font)
        self.BtnRegister.setStyleSheet("color: rgb(255, 255, 0);")
        self.BtnRegister.setObjectName("BtnRegister")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 514, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Register Page"))
        self.label.setText(_translate("MainWindow", "Register Here"))
        self.Name.setText(_translate("MainWindow", "Name"))
        self.Username.setText(_translate("MainWindow", "Username"))
        self.Password.setText(_translate("MainWindow", "Password"))
        self.ConPassword.setText(_translate("MainWindow", "Confirm Password"))
        self.BtnLogin.setText(_translate("MainWindow", "Login"))
        self.BtnRegister.setText(_translate("MainWindow", "Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
