# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegisterPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from subprocess import Popen
import sqlite3

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(424, 230)
        Form.setMinimumSize(QtCore.QSize(424, 230))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 8, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.Register_Email_LE = QtWidgets.QLineEdit(Form)
        self.Register_Email_LE.setObjectName("Register_Email_LE")
        self.gridLayout.addWidget(self.Register_Email_LE, 6, 1, 1, 1)
        self.Register_Username_LE = QtWidgets.QLineEdit(Form)
        self.Register_Username_LE.setObjectName("Register_Username_LE")
        self.gridLayout.addWidget(self.Register_Username_LE, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.Register_Password_LE = QtWidgets.QLineEdit(Form)
        self.Register_Password_LE.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Register_Password_LE.setObjectName("Register_Password_LE")
        self.gridLayout.addWidget(self.Register_Password_LE, 8, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 7, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 9, 1, 1, 1)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 10, 0, 2, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Register_Register_Btn = QtWidgets.QPushButton(Form)
        self.Register_Register_Btn.setObjectName("Register_Register_Btn")
        self.horizontalLayout_2.addWidget(self.Register_Register_Btn)
        self.Register_ReturnToLogin_Btn = QtWidgets.QPushButton(Form)
        self.Register_ReturnToLogin_Btn.setObjectName("Register_ReturnToLogin_Btn")
        self.horizontalLayout_2.addWidget(self.Register_ReturnToLogin_Btn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 12, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.Register_ReturnToLogin_Btn.clicked.connect(self.open_login_page)
        self.Register_Register_Btn.clicked.connect(self.register)



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Password"))
        self.label_3.setText(_translate("Form", "Email"))
        self.label_2.setText(_translate("Form", "Username"))
        self.label.setText(_translate("Form", "Hand Gesture Register page"))
        self.Register_Register_Btn.setText(_translate("Form", "Register"))
        self.Register_ReturnToLogin_Btn.setText(_translate("Form", "Return to login Page"))

    def register(self):
        
        email = self.Register_Email_LE.text()
        username = self.Register_Username_LE.text()
        password = self.Register_Password_LE.text()


        conn = sqlite3.connect('your_database_name.db')

        c = conn.cursor()

        c.execute("INSERT INTO users (email, username, password) VALUES (?, ?, ?)", (email, username, password))

        conn.commit()
        conn.close()

        
        QtWidgets.QMessageBox.information(self, "Registration", "You have been successfully registered!")

    def open_login_page(self):
        Form.hide()
        Popen(["python", "Test_login.py"])
        
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
